# Generated by Django 3.0.6 on 2020-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200602_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_img'),
        ),
    ]
