# Generated by Django 3.1.4 on 2022-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='url',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
