# Generated by Django 3.1.4 on 2022-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
